### ISSUE TITLE
Error: undefined method `strftime' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by wvervuurt** [bluesnotred/camt2ofx#2]
Under macOS Catalina 10.15.2 on the 2019 16" MacBook Pro, using the zsh shell, I performed the following steps:
- cloned the git repo as indicated
- `cd` into the repo and ran `sudo gem install bundler`. Output:

```
Fetching bundler-2.1.4.gem
Successfully installed bundler-2.1.4
Parsing documentation for bundler-2.1.4
Installing ri documentation for bundler-2.1.4
Done installing documentation for bundler after 2 seconds
1 gem installed
```

- `bundle install`, entering my system password to install to RubyGems. Output:

```
Installing builder 3.2.3
Using bundler 1.17.2
Using mini_portile2 2.4.0
Fetching nokogiri 1.10.4
Installing nokogiri 1.10.4 with native extensions
Fetching camt_parser 2.7.0
Installing camt_parser 2.7.0
Bundle complete! 2 Gemfile dependencies, 5 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

- `ruby camt2ofx.rb test.xml` to parse an XML file exported by ABN Amro Netherlands in the CAMT.053 format. Output (account number masked by me):

```
Start:
End:
Account: NL46ABNA0*********
Bankname: YOUR BANK
Traceback (most recent call last):
	20: from camt2ofx.rb:28:in `<main>'
	19: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:93:in `method_missing'
	18: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:68:in `tag!'
	17: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:175:in `_nested_structures'
	16: from camt2ofx.rb:44:in `block in <main>'
	15: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:93:in `method_missing'
	14: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:68:in `tag!'
	13: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:175:in `_nested_structures'
	12: from camt2ofx.rb:45:in `block (2 levels) in <main>'
	11: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:93:in `method_missing'
	10: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:68:in `tag!'
	 9: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:175:in `_nested_structures'
	 8: from camt2ofx.rb:51:in `block (3 levels) in <main>'
	 7: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:93:in `method_missing'
	 6: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:68:in `tag!'
	 5: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:175:in `_nested_structures'
	 4: from camt2ofx.rb:58:in `block (4 levels) in <main>'
	 3: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:93:in `method_missing'
	 2: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:68:in `tag!'
	 1: from /Library/Ruby/Gems/2.6.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:175:in `_nested_structures'
camt2ofx.rb:59:in `block (5 levels) in <main>': undefined method `strftime' for nil:NilClass (NoMethodError)
```

Am I doing something wrong or is this a bug in this script? Thanks in advance!

**Comment by svanesveld** [comment]
@wvervuurt I am running into the same issue. The output shows that no "Start" and "End" date was parsed (nil), which is why this crashes.

It seems that this information is usually retrieved from `<FrToDt>` field in the Camt file (see for reference [this PDF](https://www.abnamro.nl/nl/images/Content/OneShop/000_Generiek/PDF/01_Betalingsverkeer/PdfOS_Betaalvereniging_IG_CAMT_v1-0.pdf), but ABN is not including it in their Camt export. This matches with their statement in [this addendum PDF](https://www.abnamro.nl/nl/images/Content/OneShop/000_Generiek/PDF/01_Betalingsverkeer/PdfOS_Addendum_CAMT_v1-0.pdf) under 2.5:
```
2.5 FromToDate
The statement will always contain 1 day. These fields will not be filled.
```

This exporter requires this date in order to generate the file, see definitions in line 15-16 in file `camt2ofx.rb`:

```ruby
@startdate =  camt.statements.first.from_date_time  
@enddate = camt.statements.first.to_date_time 
```

As the [camt parser](https://github.com/Barzahlen/camt_parser/blob/master/lib/camt_parser/053/statement.rb#L16-L22) can't retrieve these values, the value ends up as nil.

For ABN it could probably be extracted from the value of the `<Id>` field within the `<Stmt>` container, as the value lists the account number and the date (separated by a decimal): `<Id>***********.2020-02-05</Id>`. However, that would require a change to the camt_parser code. Since ABN only provides one file per day, you may consider using the booking date of any of the transactions in the Camt file by replacing above lines with something as such:

```ruby
@startdate =  camt.statements[0].entries[0].booking_date  
@enddate = camt.statements[0].entries[0].booking_date 
```

Then, I was able to continue, running into the next problem for the ABN file which relates to the memo field:

`undefined method `remittance_information' for nil:NilClass (NoMethodError)`

Since not all transactions have remittance information (field `RmtInf\Ustrd` in the Camt file), nor a value for `end_to_end_reference` (field `Refs/EndToEndId`), this line also causes issues for ABN files. 

Alternatively, depending on what you want, you could consider throwing the full additional information in here (field `AddtlNtryInf` in the Camt file) by replacing line 75-77:

```ruby
                # MEMO
                batch_detail = "Batch payment id: #{entry.batch_detail.payment_information_identification} Transactions: #{entry.batch_detail.number_of_transactions}" if entry.batch_detail
                b.MEMO [batch_detail, entry.transactions[0].remittance_information, entry.transactions[0].end_to_end_reference].compact.join(", ")
```

with something like:

```ruby
                # MEMO
                b.MEMO.entry.additional_information.to_s
```

Probably more elegant would be to put some if/unless statements around the `b.MEMO` value to only populate it when the `remittance_information` and/or `end_to_end_reference` variables have a non-nil value.

**Comment by bluesnotred** [comment]
@wvervuurt, @svanesveld thanks for submitting your issues and detailed description. 

The issues are resolved in this feature branch:
https://github.com/bluesnotred/camt2ofx/tree/2

Unfortunately, currently I do not have a recent Rabobank export file. Could you give it a try and provide me with some feedback? Thnx!

**Comment by svanesveld** [comment]
Thanks @bluesnotred. I ran a couple of ABN files and that worked perfectly with the last update.

**Comment by bluesnotred** [comment]
Great! Both updates 5288e5f2d2e272a52c80d259d1883ac9a6e63317 and 066bb46795ec0a2592e7d3530240a1e8b77352c3 are merged into master.
